// src/moviesData.js
export const movies = [
    {
      id: "movie01",
      title: "John Wick 4",
      director: "Chad Stahelski",
      country: "Estados Unidos",
      year: 2023,
      synopsis:
        "Una exploración de las aventuras, las desgarradoras experiencias y las hazañas del legendario asesino a sueldo, John Wick.",
      banner: "/images/movie1/movie1.webp",
      trailer: "https://www.youtube.com/embed/yjRHZEUamCc",
      cast: [
        { name: "Keanu <br />Reeves", img: "/images/movie1/movie1-reparto1.webp" },
        { name: "Ian <br />McShane", img: "/images/movie1/movie1-reparto2.webp" },
        { name: "Halle <br />Berry", img: "/images/movie1/movie1-reparto3.webp" },
        { name: "Donnie <br />Yen", img: "/images/movie1/movie1-reparto4.webp" },
      ],
    },
    {
        id: "movie02",
        title: "Ant-Man and the Wasp: Quantumania",
        director: "Peyton Reed",
        country: "Estados Unidos",
        year: 2023,
        synopsis:
          " Los superhéroes se encuentran accidentalmente atrapados en el reino cuántico y deben enfrentarse a un nuevo enemigo, Kang el Conquistador.",
        banner: "/images/movie2/movie2.webp",
        trailer: "https://www.youtube.com/embed/ZlNFpri-Y40",
        cast: [
          { name: "Paul <br />Rudd", img: "/images/movie2/movie2-reparto1.webp" },
          { name: "Kathryn <br />Newton", img: "/images/movie2/movie2-reparto2.webp" },
          { name: "Jon <br />Majors", img: "/images/movie2/movie2-reparto3.webp" },
          { name: "Michelle <br />Pfeiffer", img: "/images/movie2/movie2-reparto4.webp" },
        ],
    },
    {
        id: "movie03",
        title: "Scream 4",
        director: "Matt Bettinelli-Olpin",
        country: "Estados Unidos",
        year: 2023,
        synopsis:
          " La trama principal sigue a los supervivientes de la matanza de Woodsboro en 2022 y como intentan seguir con su vida al mudarse de su pueblo natal.",
        banner: "/images/movie3/movie3.webp",
        trailer: "https://www.youtube.com/embed/JKRtyVLWV-E",
        cast: [
          { name: "Jenna<br /> Ortega", img: "/images/movie3/movie3-reparto1.webp" },
          { name: "Courtney <br />Cox", img: "/images/movie3/movie3-reparto2.webp" },
          { name: "Melissa <br />Barrera", img: "/images/movie3/movie3-reparto3.webp" },
          { name: "Roger <br />Jackson", img: "/images/movie3/movie3-reparto4.webp" },
        ],
    },
    {
      id: "movie04",
      title: "Everything Everywhere All at Once",
      director: "Dan Kwan y Daniel Scheinert",
      country: "Estados Unidos",
      year: 2022,
      synopsis:
        "Una heroína inesperada debe usar sus nuevos poderes para luchar contra los desconcertantes peligros del multiverso y así lograr salvar su mundo.",
      banner: "/images/movie4/movie4.webp",
      trailer: "https://www.youtube.com/embed/wxN1T1uxQ2g",
      cast: [
        { name: "Michelle<br /> Yeoh", img: "/images/movie4/movie4-reparto1.webp" },
        { name: "Ke Huy <br />Quan", img: "/images/movie4/movie4-reparto2.webp" },
        { name: "Jamie <br />Lee Curtis", img: "/images/movie4/movie4-reparto3.webp" },
        { name: "Stephanie <br />Hsu", img: "/images/movie4/movie4-reparto4.webp" },
      ],
    },
    {
      id: "movie05",
      title: "Demon Slayer",
      director: "Haruo Sotozaki",
      country: "Japón",
      year: 2023,
      synopsis:
        "La serie narra las desventuras de Tanjiro, un joven de un Japón feudal fantástico que se ve abocado a la venganza después de que un demonio acabe con toda su familia.",
      banner: "/images/movie5/movie5.webp",
      trailer: "https://www.youtube.com/embed/SWAMTXfqer0",
      cast: [
        { name: "Kira<br /> Buckland", img: "/images/movie5/movie5-reparto1.webp" },
        { name: "Zach <br />Aguilar", img: "/images/movie5/movie5-reparto2.webp" },
        { name: "Reba <br />Buhr", img: "/images/movie5/movie5-reparto3.webp" },
        { name: "Erica <br />Mendez", img: "/images/movie5/movie5-reparto4.webp" },
      ],
    },
    {
      id: "movie06",
      title: "The Whale",
      director: "Darren Aronofsky",
      country: "Estados Unidos",
      year: 2023,
      synopsis:
        "Un profesor de inglés, un tipo solitario que sufre obesidad mórbida, intenta restablecer el contacto con su hija en busca de perdón.",
      banner: "/images/movie6/movie6.webp",
      trailer: "https://www.youtube.com/embed/D30r0CwtIKc",
      cast: [
        { name: "Brendan<br /> Fraser", img: "/images/movie6/movie6-reparto1.webp" },
        { name: "Sadie <br />Sink", img: "/images/movie6/movie6-reparto2.webp" },
        { name: "Hong <br />Chau", img: "/images/movie6/movie6-reparto3.webp" },
        { name: "Ty <br />Simpkins", img: "/images/movie6/movie6-reparto4.webp" },
      ],
    },
    {
      id: "movie07",
      title: "Shazam! Fury of the Gods",
      director: "David F. Sandberg",
      country: "Estados Unidos",
      year: 2023,
      synopsis:
          "Billy Batson y sus hermanos adoptivos Freddy, Mary, Pedro, Eugene y Darla, también dotados de superpoderes, tienen que enfrentarse a las tres hijas de Atlas: Hespera, Kalypso y Anthea.",
      banner: "/images/movie7/movie7.webp",
      trailer: "https://www.youtube.com/embed/Zi88i4CpHe4",
      cast: [
        { name: "Zachary<br /> Levi", img: "/images/movie7/movie7-reparto1.webp" },
        { name: "Grace <br />Fulton", img: "/images/movie7/movie7-reparto2.webp" },
        { name: "Rachel <br />Zegler", img: "/images/movie7/movie7-reparto3.webp" },
        { name: "Asher <br />Angel", img: "/images/movie7/movie7-reparto4.webp" },
      ],
    },
    {
      id: "movie08",
      title: "Super Mario",
      director: "Aaron Horvath, Michael Jelenic",
      country: "Estados Unidos",
      year: 2023,
      synopsis:
          " Un fontanero llamado Mario viaja por un laberinto subterráneo con su hermano, Luigi, intentando salvar a una princesa capturada.",
      banner: "/images/movie8/movie8.webp",
      trailer: "https://www.youtube.com/embed/TnGl01FkMMo",
      cast: [
        { name: "Chris<br /> Pratt", img: "/images/movie8/movie8-reparto1.webp" },
        { name: "Anya <br />Taylor", img: "/images/movie8/movie8-reparto2.webp" },
        { name: "Jack <br />Black", img: "/images/movie8/movie8-reparto3.webp" },
        { name: "Seth <br />Rogen", img: "/images/movie8/movie8-reparto4.webp" },
      ],
    },
    {
        id: "movie13",
        title: "Machuca",
        director: "Andrés Wood",
        country: "Chile",
        year: 2004,
        synopsis:
          "Dos niños Chilenos de 12 años de diferentes clases sociales se hacen amigos en 1973. Ambos descubren el mundo del otro mientras aumentan las tensiones políticas en su país.",
        banner: "/images/movie13/movie13.webp",
        trailer: "https://www.youtube.com/embed/oNsjGH5IUJs",
        cast: [
          { name: "Manuela <br />Bartelli", img: "/images/movie13/movie13-reparto1.webp" },
          { name: "Matías <br />Quer", img: "/images/movie13/movie13-reparto2.webp" },
          { name: "Ariel <br />Mateluna", img: "/images/movie13/movie13-reparto3.webp" },
          { name: "Francisco<br /> Reyes", img: "/images/movie13/movie13-reparto4.webp" },
        ],
    },
    {
      id: "movie14",
      title: "Nueve Reinas",
      director: "Fabián Bielinsky",
      country: "Argentina",
      year: 2000,
      synopsis:
        "Juan y Marcos son dos estafadores que casualmente se ven involucrados en un asunto que los puede convertir en millonarios: tienen menos de un día para llevar a cabo un engaño que no puede fallar.",
      banner: "/images/movie14/movie14.webp",
      trailer: "https://www.youtube.com/embed/I42JYVjQkPI",
      cast: [
        { name: "Ricardo <br />Darin", img: "/images/movie14/movie14-reparto1.webp" },
        { name: "Gastón <br />Pauls", img: "/images/movie14/movie14-reparto2.webp" },
        { name: "Leticia <br />Brédice", img: "/images/movie14/movie14-reparto3.webp" },
        { name: "Tomás<br /> Fonzi", img: "/images/movie14/movie14-reparto4.webp" },
      ],
    },
    {
      id: "movie15",
      title: "Rudo & Cursi",
      director: "Carlos Cuarón",
      country: "Mexico",
      year: 2008,
      synopsis:
        " Dos hermanos, Beto, que quiere ser futbolista, y Toto, que sueña con ser cantante de música norteña, desean llevar a cabo sus sueños para mejorar su situación económica. Sin embargo, la rivalidad fraternal es lo que realmente los pone a prueba.",
      banner: "/images/movie15/movie15.webp",
      trailer: "https://www.youtube.com/embed/zAMlwcJchoQ",
      cast: [
        { name: "Gael <br />García", img: "/images/movie15/movie15-reparto1.webp" },
        { name: "Diego <br />Luna", img: "/images/movie15/movie15-reparto2.webp" },
        { name: "Guillermo <br />Francella", img: "/images/movie15/movie15-reparto3.webp" },
        { name: "Adriana<br /> Paz", img: "/images/movie15/movie15-reparto4.webp" },
      ],
    },
    {
      id: "movie16",
      title: "13 Tzameti",
      director: "Géla Babluani",
      country: "Francia",
      year: 2006,
      synopsis:
        " Sebastien es un inmigrante de Georgia en Francia que toma un puesto de albañil por un poco de dinero. Después de que su empleador muere antes de pagarle, éste roba un boleto de tren y una carta con la que cree obtendrá dinero. Pero en lugar de eso, Sebastien se vuelve el último participante de un juego mortal en el cual los jugadores apuestan a la ruleta rusa.",
      banner: "/images/movie16/movie16.webp",
      trailer: "https://www.youtube.com/embed/iHwtjI_MjF4",
      cast: [
        { name: "George <br />Babluani", img: "/images/movie16/movie16-reparto1.webp" },
        { name: "Augustin <br />Legrand", img: "/images/movie16/movie16-reparto2.webp" },
        { name: "Olga <br />Babluani", img: "/images/movie16/movie16-reparto3.webp" },
        { name: "Fred<br /> Ulysse", img: "/images/movie16/movie16-reparto4.webp" },
      ],
    },
    {
      id: "movie17",
      title: "Dogtooth",
      director: "Yorgos Lanthimos",
      country: "Grecia",
      year: 2009,
      synopsis:
        "Dogtooth (Kynódontas) es una película griega de 2009, dirigida por Yorgos Lanthimos acerca de una familia disfuncional en la que un esposo y una esposa mantienen a sus hijos ignorantes del mundo exterior en su propiedad hasta la edad adulta.",
      banner: "/images/movie17/movie17.webp",
      trailer: "https://www.youtube.com/embed/0bYpMPXXsvI",
      cast: [
        { name: "Angeliki <br />Papoulia", img: "/images/movie17/movie17-reparto1.webp" },
        { name: "Mary <br />Tsoni", img: "/images/movie17/movie17-reparto2.webp" },
        { name: "Christos <br />Passalis", img: "/images/movie17/movie17-reparto3.webp" },
        { name: "Christos<br /> Stergioglou", img: "/images/movie17/movie17-reparto4.webp" },
      ],
    },
    {
      id: "movie18",
      title: "La Vita è Bella",
      director: "Roberto Benigni",
      country: "Italia",
      year: 1997,
      synopsis:
        "Un hombre construye una elaborada fantasía para proteger a su hijo en un campo de concentración nazi.",
      banner: "/images/movie18/movie18.webp",
      trailer: "https://www.youtube.com/embed/8CTjcVr9Iao",
      cast: [
        { name: "Roberto <br />Benigni", img: "/images/movie18/movie18-reparto1.webp" },
        { name: "Nicoletta <br />Braschi", img: "/images/movie18/movie18-reparto2.webp" },
        { name: "Giorgio <br />Cantarini", img: "/images/movie18/movie18-reparto3.webp" },
        { name: "Giustino<br /> Durano", img: "/images/movie18/movie18-reparto4.webp" },
      ],
    },
    {
      id: "movie19",
      title: "Parasite",
      director: "Bong Joon-ho",
      country: "Corea del Sur",
      year: 2019,
      synopsis:
        "Tanto Gi Taek como su familia están sin trabajo. Cuando su hijo mayor, Gi Woo, empieza a impartir clases particulares en la adinerada casa de los Park, las dos familias, que tienen mucho en común pese a pertenecer a dos mundos totalmente distintos, entablan una relación de resultados imprevisibles.",
      banner: "/images/movie19/movie19.webp",
      trailer: "https://www.youtube.com/embed/9kLlmWPilSE",
      cast: [
        { name: "Song <br />Kang-ho", img: "/images/movie19/movie19-reparto1.webp" },
        { name: "Park <br />So-dam", img: "/images/movie19/movie19-reparto2.webp" },
        { name: "Choi <br />Woo-shik", img: "/images/movie19/movie19-reparto3.webp" },
        { name: "Jang<br /> Hye-jin", img: "/images/movie19/movie19-reparto4.webp" },
      ],
    },
    {
      id: "movie20",
      title: "Bar Bahar",
      director: "Maysaloun Hamoudr",
      country: "Palestina",
      year: 2016,
      synopsis:
        "Bar Bahar (In Between) es una película franco-palestina escrita y dirigida por Maysaloun Hamoud, estrenada en 2016 en el Festival de Cine de Toronto.",
      banner: "/images/movie20/movie20.webp",
      trailer: "https://www.youtube.com/embed/4-gFE4UZA4E",
      cast: [
        { name: "Sana <br />Jammelieh", img: "/images/movie20/movie20-reparto1.webp" },
        { name: "Shaden <br />Kanboura", img: "/images/movie20/movie20-reparto2.webp" },
        { name: "Samar <br />Qupty", img: "/images/movie20/movie20-reparto3.webp" },
        { name: "Firas<br /> Nasser", img: "/images/movie20/movie20-reparto4.webp" },
      ],
    },
    {
      id: "movie21",
      title: "Oldboy",
      director: "Chan-Wook Park",
      country: "Corea del Sur",
      year: 2003,
      synopsis:
        "Dae-Su es un hombre de negocios que, sin motivo aparente, es secuestrado y confinado en una celda con la única compañía de un televisor. Quince años más tarde, es liberado junto a una gran cantidad de dinero y un teléfono celular.",
      banner: "/images/movie21/movie21.webp",
      trailer: "https://www.youtube.com/embed/tAaBkFChaRg",
      cast: [
        { name: "Choi <br />Min Sik", img: "/images/movie21/movie21-reparto1.webp" },
        { name: "Kang <br />Hye-jung", img: "/images/movie21/movie21-reparto2.webp" },
        { name: "Yoo <br />Ji-tae", img: "/images/movie21/movie21-reparto3.webp" },
        { name: "Yoon<br /> Jin-seo", img: "/images/movie21/movie21-reparto4.webp" },
      ],
    },
    {
      id: "movie22",
      title: "Persepolis",
      director: "Marjane Satrapi",
      country: "Francia",
      year: 2007,
      synopsis:
        "Una niña iraní atestigua el control fundamentalista de su país y se rebela contra sus políticas estrictas, especialmente las referentes a las mujeres.",
      banner: "/images/movie22/movie22.webp",
      trailer: "https://www.youtube.com/embed/3PXHeKuBzPY",
      cast: [
        { name: "Chiara <br />Mastroianni", img: "/images/movie22/movie22-reparto1.webp" },
        { name: "Chaterine <br />Deneuve", img: "/images/movie22/movie22-reparto2.webp" },
        { name: "Danielle <br />Darrieux", img: "/images/movie22/movie22-reparto3.webp" },
        { name: "Simon<br /> Abkarian", img: "/images/movie22/movie22-reparto4.webp" },
      ],
    },
    {
      id: "movie23",
      title: "Mary and Max",
      director: " Adam Elliot",
      country: "Australia",
      year: 2009,
      synopsis:
        "Una solitaria chica Australiana y un anciano judío desarrollan en Nueva York una singular amistad a través de cartas.",
      banner: "/images/movie23/movie23.webp",
      trailer: "https://www.youtube.com/embed/p1W_mpSydYI",
      cast: [
        { name: "Toni <br />Collette", img: "/images/movie23/movie23-reparto1.webp" },
        { name: "Phillip <br />S. Hoffman", img: "/images/movie23/movie23-reparto2.webp" },
        { name: "Eric <br />Bana", img: "/images/movie23/movie23-reparto3.webp" },
        { name: "Bethany<br /> Whitmore", img: "/images/movie23/movie23-reparto4.webp" },
      ],
    },
    {
      id: "movie24",
      title: "Le Magasin des Suicides",
      director: " Jean Teulé",
      country: "Francia",
      year: 2006,
      synopsis:
        " The Suicide Shop es una novela de comedia negra de 2006 del escritor francés Jean Teulé. Está ambientado en una futura ciudad casi apocalíptica en un mundo que sufre los estragos del cambio climático severo, donde casi todo el mundo está deprimido.",
      banner: "/images/movie24/movie24.webp",
      trailer: "https://www.youtube.com/embed/aFgT0sEqrso",
      cast: [
        { name: "Isabelle <br />Spade", img: "/images/movie24/movie24-reparto1.webp" },
        { name: "Kacey <br />Klein", img: "/images/movie24/movie24-reparto2.webp" },
        { name: "Isabelle <br />Giami", img: "/images/movie24/movie24-reparto3.webp" },
        { name: "Bernard<br /> Alane", img: "/images/movie24/movie24-reparto4.webp" },
      ],
    },
    {
      id: "movie25",
      title: "Heat",
      director: "Michael Mann",
      country: "Estados Unidos",
      year: 1995,
      synopsis:
        "Un veterano ladrón de bancos decide preparar un último y sofisticado robo con la intención de retirarse, pero un policía de métodos expeditivos, cuya vida privada es una pesadilla, se propone impedírselo.",
      banner: "/images/movie25/movie25.webp",
      trailer: "https://www.youtube.com/embed/2GfZl4kuVNI",
      cast: [
        { name: "Robert <br />De Niro", img: "/images/movie25/movie25-reparto1.webp" },
        { name: "Al <br />Pacino", img: "/images/movie25/movie25-reparto2.webp" },
        { name: "Val <br />Kilmer", img: "/images/movie25/movie25-reparto3.webp" },
        { name: "Natalie<br /> Portman", img: "/images/movie25/movie25-reparto4.webp" },
      ],
    },
    {
      id: "movie26",
      title: "Trainspotting",
      director: "Danny Boyle",
      country: "Reino Unido",
      year: 1996,
      synopsis:
        "Unos jóvenes de Edimburgo mantienen una dependencia intermitente a la heroína. Basado en la novela de Irvine Welsh.",
      banner: "/images/movie26/movie26.webp",
      trailer: "https://www.youtube.com/embed/8LuxOYIpu-I",
      cast: [
        { name: "Ewan <br />McGregor", img: "/images/movie26/movie26-reparto1.webp" },
        { name: "Jonny <br />Lee Miller", img: "/images/movie26/movie26-reparto2.webp" },
        { name: "Robert <br />Carlyle", img: "/images/movie26/movie26-reparto3.webp" },
        { name: "Kelly<br /> Macdonald", img: "/images/movie26/movie26-reparto4.webp" },
      ],
    },
    {
      id: "movie27",
      title: "Pi: Faith in Chaos",
      director: "Darren Aronofsky",
      country: "Estados Unidos",
      year: 1998,
      synopsis:
        "Max es un matemático que está a punto de decodificar el sistema numérico del mercado bursátil. Sin embargo, antes debe encontrar el valor del número pi. Una firma de Wall Street y una secta judía perseguirán a Max para quedarse con su descubrimiento.",
      banner: "/images/movie27/movie27.webp",
      trailer: "https://www.youtube.com/embed/jo18VIoR2xU",
      cast: [
        { name: "Sean <br />Gullette", img: "/images/movie27/movie27-reparto1.webp" },
        { name: "Mark <br />Margolis", img: "/images/movie27/movie27-reparto2.webp" },
        { name: "Samia <br />Shoaib", img: "/images/movie27/movie27-reparto3.webp" },
        { name: "Clint<br /> Mansell", img: "/images/movie27/movie27-reparto4.webp" },
      ],
    },
    {
      id: "movie28",
      title: "Snatch",
      director: "Guy Ritchie",
      country: "Reino Unido",
      year: 2000,
      synopsis:
        "Un grupo de ladrones lucha para encontrar un diamante robado de 84 quilates con un valor incalculable.",
      banner: "/images/movie28/movie28.webp",
      trailer: "https://www.youtube.com/embed/9Jar2XkBboo",
      cast: [
        { name: "Jason <br />Statham", img: "/images/movie28/movie28-reparto1.webp" },
        { name: "Brad <br />Pitt", img: "/images/movie28/movie28-reparto2.webp" },
        { name: "Vinnie <br />Jones", img: "/images/movie28/movie28-reparto3.webp" },
        { name: "Stephen<br /> Graham", img: "/images/movie28/movie28-reparto4.webp" },
      ],
    },
    {
      id: "movie29",
      title: "A Clockwork Orange",
      director: "Stanley Kubrick",
      country: "Reino Unido",
      year: 1972,
      synopsis:
        "Un criminal en la Inglaterra del futuro pasa una serie de procesos experimentales para corregir sus impulsos violentos.",
      banner: "/images/movie29/movie29.webp",
      trailer: "https://www.youtube.com/embed/T54uZPI4Z8A",
      cast: [
        { name: "Malcom <br />McDowell", img: "/images/movie29/movie29-reparto1.webp" },
        { name: "Adrienne <br />Corri", img: "/images/movie29/movie29-reparto2.webp" },
        { name: "Warren <br />Clark", img: "/images/movie29/movie29-reparto3.webp" },
        { name: "Patrick<br /> Magee", img: "/images/movie29/movie29-reparto4.webp" },
      ],
    },
    {
      id: "movie30",
      title: "Braveheart",
      director: "Mel Gibson",
      country: "Estados Unidos",
      year: 1995,
      synopsis:
        "William Wallace, un indómito rebelde escocés, dirige una revuelta contra los ingleses con el objetivo de independizar a Escocia de Inglaterra para librar a su pueblo de la tiranía del monarca Eduardo I.",
      banner: "/images/movie30/movie30.webp",
      trailer: "https://www.youtube.com/embed/1NJO0jxBtMo",
      cast: [
        { name: "Mel <br />Gibson", img: "/images/movie30/movie30-reparto1.webp" },
        { name: "Sophie <br />Marceau", img: "/images/movie30/movie30-reparto2.webp" },
        { name: "Brendan <br />Gleeson", img: "/images/movie30/movie30-reparto3.webp" },
        { name: "Tommy<br /> Flanagan", img: "/images/movie30/movie30-reparto4.webp" },
      ],
    },
    {
        id: "movie31",
        title: "Pulp Fiction",
        director: "Quentin Tarantino",
        country: "Estados Unidos",
        year: 1994,
        synopsis:
          "La vida de un boxeador, dos sicarios, la esposa de un gánster y dos bandidos se entrelaza en una historia de violencia y redención.",
        banner: "/images/movie31/movie31.webp",
        trailer: "https://www.youtube.com/embed/s7EdQ4FqbhY",
        cast: [
          { name: "John <br />Travolta", img: "/images/movie31/movie31-reparto1.webp" },
          { name: "Samuel<br /> L Jackson", img: "/images/movie31/movie31-reparto2.webp" },
          { name: "Uma<br /> Thurman", img: "/images/movie31/movie31-reparto3.webp" },
          { name: "Bruce <br />Willis", img: "/images/movie31/movie31-reparto4.webp" },
        ],
    },
    {
      id: "movie32",
      title: "Inglourious Basterds",
      director: "Quentin Tarantino",
      country: "Estados Unidos",
      year: 2009,
      synopsis:
        " El oficial aliado, teniente Aldo Raine, ensambla un equipo de soldados judíos para cometer actos violentos en contra de los nazis. Sus destinos convergen con la dueña de teatro Shosanna Dreyfus, quien busca vengar la ejecución de su familia.",
      banner: "/images/movie32/movie32.webp",
      trailer: "https://www.youtube.com/embed/KnrRy6kSFF0",
      cast: [
        { name: "Christoph <br />Waltz", img: "/images/movie32/movie32-reparto1.webp" },
        { name: "Brad<br /> Pitt", img: "/images/movie32/movie32-reparto2.webp" },
        { name: "Mélanie<br /> Laurent", img: "/images/movie32/movie32-reparto3.webp" },
        { name: "Michael <br />Fassbender", img: "/images/movie32/movie32-reparto4.webp" },
      ],
      },
      {
      id: "movie33",
      title: "Django Unchained",
      director: "Quentin Tarantino",
      country: "Estados Unidos",
      year: 2012,
      synopsis:
        ": Un exesclavo une fuerzas con un cazador de recompensas alemán que lo liberó y lo ayuda a buscar a los criminales más buscados del sur de los Estados Unidos, con la esperanza de reencontrarse con su esposa.",
      banner: "/images/movie33/movie33.webp",
      trailer: "https://www.youtube.com/embed/0fUCuvNlOCg",
      cast: [
        { name: "Jamie <br />Foxx", img: "/images/movie33/movie33-reparto1.webp" },
        { name: "Christoph<br /> Waltz", img: "/images/movie33/movie33-reparto2.webp" },
        { name: "Leonardo<br /> Dicaprio", img: "/images/movie33/movie33-reparto3.webp" },
        { name: "Samuel <br />L. Jackson", img: "/images/movie33/movie33-reparto4.webp" },
      ],
    },
  ];