// src/moviesData.js
export const movies = [
    {
      id: "movie01",
      title: "John Wick 4",
      director: "Chad Stahelski",
      country: "Estados Unidos",
      year: 2023,
      synopsis:
        "Una exploración de las aventuras, las desgarradoras experiencias y las hazañas del legendario asesino a sueldo, John Wick.",
      banner: "/images/movie1/movie1.webp",
      trailer: "https://www.youtube.com/embed/yjRHZEUamCc",
      cast: [
        { name: "Keanu <br />Reeves", img: "/images/movie1/movie1-reparto1.webp" },
        { name: "Ian <br />McShane", img: "/images/movie1/movie1-reparto2.webp" },
        { name: "Halle <br />Berry", img: "/images/movie1/movie1-reparto3.webp" },
        { name: "Donnie <br />Yen", img: "/images/movie1/movie1-reparto4.webp" },
      ],
    },
    {
        id: "movie02",
        title: "Ant-Man and the Wasp: Quantumania",
        director: "Peyton Reed",
        country: "Estados Unidos",
        year: 2023,
        synopsis:
          " Los superhéroes se encuentran accidentalmente atrapados en el reino cuántico y deben enfrentarse a un nuevo enemigo, Kang el Conquistador.",
        banner: "/images/movie2/movie2.webp",
        trailer: "https://www.youtube.com/embed/ZlNFpri-Y40",
        cast: [
          { name: "Paul <br />Rudd", img: "/images/movie2/movie2-reparto1.webp" },
          { name: "Kathryn <br />Newton", img: "/images/movie2/movie2-reparto2.webp" },
          { name: "Jon <br />Majors", img: "/images/movie2/movie2-reparto3.webp" },
          { name: "Michelle <br />Pfeiffer", img: "/images/movie2/movie2-reparto4.webp" },
        ],
    },
    {
        id: "movie03",
        title: "Scream 4",
        director: "Matt Bettinelli-Olpin",
        country: "Estados Unidos",
        year: 2023,
        synopsis:
          " La trama principal sigue a los supervivientes de la matanza de Woodsboro en 2022 y como intentan seguir con su vida al mudarse de su pueblo natal.",
        banner: "/images/movie3/movie3.webp",
        trailer: "https://www.youtube.com/embed/JKRtyVLWV-E",
        cast: [
          { name: "Jenna<br /> Ortega", img: "/images/movie3/movie3-reparto1.webp" },
          { name: "Courtney <br />Cox", img: "/images/movie3/movie3-reparto2.webp" },
          { name: "Melissa <br />Barrera", img: "/images/movie3/movie3-reparto3.webp" },
          { name: "Roger <br />Jackson", img: "/images/movie3/movie3-reparto4.webp" },
        ],
    },
    {
      id: "movie04",
      title: "Everything Everywhere All at Once",
      director: "Dan Kwan y Daniel Scheinert",
      country: "Estados Unidos",
      year: 2022,
      synopsis:
        "Una heroína inesperada debe usar sus nuevos poderes para luchar contra los desconcertantes peligros del multiverso y así lograr salvar su mundo.",
      banner: "/images/movie4/movie4.webp",
      trailer: "https://www.youtube.com/embed/wxN1T1uxQ2g",
      cast: [
        { name: "Michelle<br /> Yeoh", img: "/images/movie4/movie4-reparto1.webp" },
        { name: "Ke Huy <br />Quan", img: "/images/movie4/movie4-reparto2.webp" },
        { name: "Jamie <br />Lee Curtis", img: "/images/movie4/movie4-reparto3.webp" },
        { name: "Stephanie <br />Hsu", img: "/images/movie4/movie4-reparto4.webp" },
      ],
    },
    {
      id: "movie05",
      title: "Demon Slayer",
      director: "Haruo Sotozaki",
      country: "Japón",
      year: 2023,
      synopsis:
        "La serie narra las desventuras de Tanjiro, un joven de un Japón feudal fantástico que se ve abocado a la venganza después de que un demonio acabe con toda su familia.",
      banner: "/images/movie5/movie5.webp",
      trailer: "https://www.youtube.com/embed/SWAMTXfqer0",
      cast: [
        { name: "Kira<br /> Buckland", img: "/images/movie5/movie5-reparto1.webp" },
        { name: "Zach <br />Aguilar", img: "/images/movie5/movie5-reparto2.webp" },
        { name: "Reba <br />Buhr", img: "/images/movie5/movie5-reparto3.webp" },
        { name: "Erica <br />Mendez", img: "/images/movie5/movie5-reparto4.webp" },
      ],
    },
    {
      id: "movie06",
      title: "The Whale",
      director: "Darren Aronofsky",
      country: "Estados Unidos",
      year: 2023,
      synopsis:
        "Un profesor de inglés, un tipo solitario que sufre obesidad mórbida, intenta restablecer el contacto con su hija en busca de perdón.",
      banner: "/images/movie6/movie6.webp",
      trailer: "https://www.youtube.com/embed/D30r0CwtIKc",
      cast: [
        { name: "Brendan<br /> Fraser", img: "/images/movie6/movie6-reparto1.webp" },
        { name: "Sadie <br />Sink", img: "/images/movie6/movie6-reparto2.webp" },
        { name: "Hong <br />Chau", img: "/images/movie6/movie6-reparto3.webp" },
        { name: "Ty <br />Simpkins", img: "/images/movie6/movie6-reparto4.webp" },
      ],
    },
    {
      id: "movie07",
      title: "Shazam! Fury of the Gods",
      director: "David F. Sandberg",
      country: "Estados Unidos",
      year: 2023,
      synopsis:
          "Billy Batson y sus hermanos adoptivos Freddy, Mary, Pedro, Eugene y Darla, también dotados de superpoderes, tienen que enfrentarse a las tres hijas de Atlas: Hespera, Kalypso y Anthea.",
      banner: "/images/movie7/movie7.webp",
      trailer: "https://www.youtube.com/embed/Zi88i4CpHe4",
      cast: [
        { name: "Zachary<br /> Levi", img: "/images/movie7/movie7-reparto1.webp" },
        { name: "Grace <br />Fulton", img: "/images/movie7/movie7-reparto2.webp" },
        { name: "Rachel <br />Zegler", img: "/images/movie7/movie7-reparto3.webp" },
        { name: "Asher <br />Angel", img: "/images/movie7/movie7-reparto4.webp" },
      ],
    },
    {
      id: "movie08",
      title: "Super Mario",
      director: "Aaron Horvath, Michael Jelenic",
      country: "Estados Unidos",
      year: 2023,
      synopsis:
          " Un fontanero llamado Mario viaja por un laberinto subterráneo con su hermano, Luigi, intentando salvar a una princesa capturada.",
      banner: "/images/movie8/movie8.webp",
      trailer: "https://www.youtube.com/embed/TnGl01FkMMo",
      cast: [
        { name: "Chris<br /> Pratt", img: "/images/movie8/movie8-reparto1.webp" },
        { name: "Anya <br />Taylor", img: "/images/movie8/movie8-reparto2.webp" },
        { name: "Jack <br />Black", img: "/images/movie8/movie8-reparto3.webp" },
        { name: "Seth <br />Rogen", img: "/images/movie8/movie8-reparto4.webp" },
      ],
    },
    {
        id: "movie13",
        title: "Machuca",
        director: "Andrés Wood",
        country: "Chile",
        year: 2004,
        synopsis:
          "Dos niños Chilenos de 12 años de diferentes clases sociales se hacen amigos en 1973. Ambos descubren el mundo del otro mientras aumentan las tensiones políticas en su país.",
        banner: "/images/movie13/movie13.webp",
        trailer: "https://www.youtube.com/embed/oNsjGH5IUJs",
        cast: [
          { name: "Manuela <br />Bartelli", img: "/images/movie13/movie13-reparto1.webp" },
          { name: "Matías <br />Quer", img: "/images/movie13/movie13-reparto2.webp" },
          { name: "Ariel <br />Mateluna", img: "/images/movie13/movie13-reparto3.webp" },
          { name: "Francisco<br /> Reyes", img: "/images/movie13/movie13-reparto4.webp" },
        ],
    },
    {
      id: "movie14",
      title: "Nueve Reinas",
      director: "Fabián Bielinsky",
      country: "Argentina",
      year: 2000,
      synopsis:
        "Juan y Marcos son dos estafadores que casualmente se ven involucrados en un asunto que los puede convertir en millonarios: tienen menos de un día para llevar a cabo un engaño que no puede fallar.",
      banner: "/images/movie14/movie14.webp",
      trailer: "https://www.youtube.com/embed/I42JYVjQkPI",
      cast: [
        { name: "Ricardo <br />Darin", img: "/images/movie14/movie14-reparto1.webp" },
        { name: "Gastón <br />Pauls", img: "/images/movie14/movie14-reparto2.webp" },
        { name: "Leticia <br />Brédice", img: "/images/movie14/movie14-reparto3.webp" },
        { name: "Tomás<br /> Fonzi", img: "/images/movie14/movie14-reparto4.webp" },
      ],
    },
    {
      id: "movie15",
      title: "Rudo & Cursi",
      director: "Carlos Cuarón",
      country: "Mexico",
      year: 2008,
      synopsis:
        " Dos hermanos, Beto, que quiere ser futbolista, y Toto, que sueña con ser cantante de música norteña, desean llevar a cabo sus sueños para mejorar su situación económica. Sin embargo, la rivalidad fraternal es lo que realmente los pone a prueba.",
      banner: "/images/movie15/movie15.webp",
      trailer: "https://www.youtube.com/embed/zAMlwcJchoQ",
      cast: [
        { name: "Gael <br />García", img: "/images/movie15/movie15-reparto1.webp" },
        { name: "Diego <br />Luna", img: "/images/movie15/movie15-reparto2.webp" },
        { name: "Guillermo <br />Francella", img: "/images/movie15/movie15-reparto3.webp" },
        { name: "Adriana<br /> Paz", img: "/images/movie15/movie15-reparto4.webp" },
      ],
    },
    {
        id: "movie31",
        title: "Pulp Fiction",
        director: "Quentin Tarantino",
        country: "Estados Unidos",
        year: 1994,
        synopsis:
          "La vida de un boxeador, dos sicarios, la esposa de un gánster y dos bandidos se entrelaza en una historia de violencia y redención.",
        banner: "/images/movie31/movie31.webp",
        trailer: "https://www.youtube.com/embed/s7EdQ4FqbhY",
        cast: [
          { name: "John <br />Travolta", img: "/images/movie31/movie31-reparto1.webp" },
          { name: "Samuel<br /> L Jackson", img: "/images/movie31/movie31-reparto2.webp" },
          { name: "Uma<br /> Thurman", img: "/images/movie31/movie31-reparto3.webp" },
          { name: "Bruce <br />Willis", img: "/images/movie31/movie31-reparto4.webp" },
        ],
    },
    {
      id: "movie32",
      title: "Inglourious Basterds",
      director: "Quentin Tarantino",
      country: "Estados Unidos",
      year: 2009,
      synopsis:
        " El oficial aliado, teniente Aldo Raine, ensambla un equipo de soldados judíos para cometer actos violentos en contra de los nazis. Sus destinos convergen con la dueña de teatro Shosanna Dreyfus, quien busca vengar la ejecución de su familia.",
      banner: "/images/movie32/movie32.webp",
      trailer: "https://www.youtube.com/embed/KnrRy6kSFF0",
      cast: [
        { name: "Christoph <br />Waltz", img: "/images/movie32/movie32-reparto1.webp" },
        { name: "Brad<br /> Pitt", img: "/images/movie32/movie32-reparto2.webp" },
        { name: "Mélanie<br /> Laurent", img: "/images/movie32/movie32-reparto3.webp" },
        { name: "Michael <br />Fassbender", img: "/images/movie32/movie32-reparto4.webp" },
      ],
      },
      {
      id: "movie33",
      title: "Django Unchained",
      director: "Quentin Tarantino",
      country: "Estados Unidos",
      year: 2012,
      synopsis:
        ": Un exesclavo une fuerzas con un cazador de recompensas alemán que lo liberó y lo ayuda a buscar a los criminales más buscados del sur de los Estados Unidos, con la esperanza de reencontrarse con su esposa.",
      banner: "/images/movie33/movie33.webp",
      trailer: "https://www.youtube.com/embed/0fUCuvNlOCg",
      cast: [
        { name: "Jamie <br />Foxx", img: "/images/movie33/movie33-reparto1.webp" },
        { name: "Christoph<br /> Waltz", img: "/images/movie33/movie33-reparto2.webp" },
        { name: "Leonardo<br /> Dicaprio", img: "/images/movie33/movie33-reparto3.webp" },
        { name: "Samuel <br />L. Jackson", img: "/images/movie33/movie33-reparto4.webp" },
      ],
    },
  ];